# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import re
import os
from datetime import datetime
from datetime import timedelta



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(789, 393)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(0, 40, 401, 351))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 85, 127);")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.name = QtWidgets.QLineEdit(self.groupBox)
        self.name.setGeometry(QtCore.QRect(120, 30, 261, 31))
        self.name.setObjectName("name")
        self.desc = QtWidgets.QTextEdit(self.groupBox)
        self.desc.setGeometry(QtCore.QRect(120, 100, 261, 51))
        self.desc.setObjectName("desc")
        self.tdate = QtWidgets.QDateEdit(self.groupBox)
        self.tdate.setGeometry(QtCore.QRect(120, 240, 81, 22))
        self.tdate.setCurrentSectionIndex(0)
        self.tdate.setObjectName("tdate")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 180, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.tstatus = QtWidgets.QComboBox(self.groupBox)
        self.tstatus.setGeometry(QtCore.QRect(120, 180, 81, 21))
        self.tstatus.setObjectName("tstatus")
        self.tstatus.addItem("Task-To-Do")
        self.tstatus.addItem("In-Progress")
        self.tstatus.addItem("Completed")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 240, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 290, 401, 41))
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.tadd = QtWidgets.QPushButton(self.groupBox_2)
        self.tadd.setGeometry(QtCore.QRect(10, 10, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.tadd.setFont(font)
        self.tadd.setStyleSheet("color: rgb(0, 85, 127);")
        self.tadd.setObjectName("tadd")
        self.tupdate = QtWidgets.QPushButton(self.groupBox_2)
        self.tupdate.setGeometry(QtCore.QRect(100, 10, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.tupdate.setFont(font)
        self.tupdate.setStyleSheet("color: rgb(85, 85, 127);\n"
"color: rgb(0, 85, 127);")
        self.tupdate.setObjectName("tupdate")
        self.tdisp = QtWidgets.QPushButton(self.groupBox_2)
        self.tdisp.setGeometry(QtCore.QRect(200, 10, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.tdisp.setFont(font)
        self.tdisp.setStyleSheet("color: rgb(0, 85, 127);")
        self.tdisp.setObjectName("tdisp")
        self.tdelete = QtWidgets.QPushButton(self.groupBox_2)
        self.tdelete.setGeometry(QtCore.QRect(310, 10, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.tdelete.setFont(font)
        self.tdelete.setStyleSheet("color: rgb(0, 85, 127);")
        self.tdelete.setObjectName("tdelete")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(400, 0, 401, 391))
        self.groupBox_3.setStyleSheet("color: rgb(0, 85, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(0, 130, 111, 20))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(0, 260, 101, 20))
        self.label_8.setObjectName("label_8")
        self.tpro = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.tpro.setGeometry(QtCore.QRect(0, 150, 381, 101))
        self.tpro.setStyleSheet("color: rgb(181, 181, 0);")
        self.tpro.setPlainText("")
        self.tpro.setObjectName("tpro")
        self.tdo = QtWidgets.QTextEdit(self.groupBox_3)
        self.tdo.setGeometry(QtCore.QRect(0, 30, 381, 101))
        self.tdo.setStyleSheet("color: rgb(170, 0, 0);")
        self.tdo.setObjectName("tdo")
        self.tcomp = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.tcomp.setGeometry(QtCore.QRect(0, 280, 381, 101))
        self.tcomp.setStyleSheet("color: rgb(0, 170, 0);")
        self.tcomp.setPlainText("")
        self.tcomp.setObjectName("tcomp")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 0, 401, 41))
        self.groupBox_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(150, 10, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color: rgb(85, 0, 0);")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def Add(self):
     self.tcomp.clear()
     self.tpro.clear()
     self.tdo.clear()
     self.tdisp.setEnabled(True)      
     try: 
        if self.name.text():
            _name=self.name.text()
            _desc=self.desc.toPlainText()
            _date=str(self.tdate.date())
            _status=self.tstatus.currentText()
     
            fr=open("task.txt","a")
            
            fr.writelines(_name)
            fr.writelines("---"+_desc)
            fr.writelines("---"+_date)
            fr.writelines(_status)
            fr.writelines("\n")
        

            self.tcomp.clear()
            self.tpro.clear()
            self.tdo.clear()
            self.name.clear()
            self.desc.clear() 
            self.tdate.clear()
            
             
        else:          
           print("Wrong Input") 
     except:
      print("Oops! something error")
        
    


        
    def Disp(self):
      with open("task.txt") as infile:
         for line in infile:
           #print(line)
           m = re.findall('\(.*?\)',line)
           #print(m)
           for ex in m:
             a2 = ex.replace('(','').replace(')','').replace(' ','-').replace(',','')  
             str1=(str(a2))
              
             print(str1)
           
           ExpectedDate = "2022/4/20"
           ExpectedDate =str(datetime.strptime(ExpectedDate, "%Y/%m/%d")) 
           ExpectedDate= re.sub('00:00:00', '', ExpectedDate)
           ExpectedDate=ExpectedDate[:5]+ExpectedDate[6:]
           print(ExpectedDate) 
           if str1 > ExpectedDate:
            print("Date missed")
           else:
            print("Date not missed")
      
      try:
         
         self.tdisp.setEnabled(False)
         with open("task.txt") as fo:
          for each in fo:
             if "Completed" in each:
                str1=each.replace('Completed','')
                str11=str1.replace('PyQt5.QtCore.QDate','')
                str21=re.sub("[()]","", str11) 
                self.tcomp.insertPlainText(str21)  
             elif "In-Progress" in each:
                  str2=each.replace('In-Progress','')
                  str12=str2.replace('PyQt5.QtCore.QDate','')
                  str22=re.sub("[()]","", str12)    
                  self.tpro.insertPlainText(str22)
             elif "Task-To-Do" in each:
                 str3=each.replace('Task-To-Do','')
                 str13=str3.replace('PyQt5.QtCore.QDate','')
                 str33=re.sub("[()]","", str13)     
                 self.tdo.insertPlainText(str33)
             
      except:
                 print("Oops! something error")



    def Update(self):
        self.tdisp.setEnabled(True)
        
        self.tcomp.clear()
        self.tpro.clear()
        self.tdo.clear()  
        try:
         if self.name.text():      
            self.tdisp.setEnabled(True)
            self.tcomp.clear()
            self.tpro.clear()
            self.tdo.clear()    
            self.Dele()
            fr=open("task.txt","a")
            fr.writelines("\n")
            self.Add()
            print("Task Updated")
         else:          
           print("Wrong Input")   
        except:
         print("Oops! something error")   



    def Dele(self):
        self.tdisp.setEnabled(True)
        
        self.tcomp.clear()
        self.tpro.clear()
        self.tdo.clear()    
        try:
         if self.name.text():    
            with open('task.txt', 'r') as fr:
                lines = fr.readlines()
                ptr = 1
            with open('task.txt', 'w') as fw:
                search=str(self.name.text())
                print(search)        
                for line in lines:
                  if line.find(search) == -1:
                    fw.write(line)
                    
            print("Deleted")
         else:          
           print("Wrong Input")   
        except:
            print("Oops! something error")


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "USER ACTIVITY"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#55007f;\">Task Name :</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#55007f;\">Task Desciption :</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#55007f;\">Task Status :</span></p></body></html>"))
        self.tstatus.setAccessibleName(_translate("Form", "<html><head/><body><p>To-Do</p><p>Completed</p><p>In-Progress</p><p><br/></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#55007f;\">Task  Date :</span></p></body></html>"))
        self.tadd.setText(_translate("Form", "ADD TASK"))
        self.tupdate.setText(_translate("Form", "UPDATE TASK"))
        self.tdisp.setText(_translate("Form", "DISPLAY TASK"))
        self.tdelete.setText(_translate("Form", "DELETE TASK"))
        self.groupBox_3.setTitle(_translate("Form", "SHOW TASK STATUS "))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; color:#aa0000;\">Task_To_Do</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; color:#b5b93d;\">Task_In_Progress</span></p></body></html>"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; color:#005500;\">Task_Completed</span></p></body></html>"))
        self.tdo.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; color:#550000;\">TASK MANAGER</span></p></body></html>"))
        self.tadd.clicked.connect(self.Add)
        self.tdisp.clicked.connect(self.Disp)
        self.tupdate.clicked.connect(self.Update)
        self.tdelete.clicked.connect(self.Dele)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
