# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emp.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
import psycopg2

#import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidget,QTableWidgetItem
 


conn = psycopg2.connect(database="restDB", user = "postgres", password = "KEDAR", host = "localhost", port = "5432")
print("Opened database successfully")






class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(614, 442)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 40, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(85, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(340, 40, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(85, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 80, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(85, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(340, 80, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(85, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 120, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(85, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.emp_id = QtWidgets.QLineEdit(Dialog)
        self.emp_id.setGeometry(QtCore.QRect(150, 40, 141, 20))
        self.emp_id.setObjectName("emp_id")
        self.emp_name = QtWidgets.QLineEdit(Dialog)
        self.emp_name.setGeometry(QtCore.QRect(460, 40, 141, 20))
        self.emp_name.setObjectName("emp_name")
        self.emp_age = QtWidgets.QLineEdit(Dialog)
        self.emp_age.setGeometry(QtCore.QRect(150, 80, 141, 20))
        self.emp_age.setObjectName("emp_age")
        self.emp_add = QtWidgets.QLineEdit(Dialog)
        self.emp_add.setGeometry(QtCore.QRect(460, 80, 141, 20))
        self.emp_add.setObjectName("emp_add")
        self.emp_sal = QtWidgets.QLineEdit(Dialog)
        self.emp_sal.setGeometry(QtCore.QRect(150, 120, 141, 20))
        self.emp_sal.setObjectName("emp_sal")
        self.add = QtWidgets.QPushButton(Dialog)
        self.add.setGeometry(QtCore.QRect(410, 120, 91, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.add.setFont(font)
        self.add.setStyleSheet("color: rgb(97, 32, 161);")
        self.add.setObjectName("add")
        self.update = QtWidgets.QPushButton(Dialog)
        self.update.setGeometry(QtCore.QRect(310, 120, 91, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.update.setFont(font)
        self.update.setStyleSheet("color: rgb(97, 32, 161);")
        self.update.setObjectName("update")
        self.delete_2 = QtWidgets.QPushButton(Dialog)
        self.delete_2.setGeometry(QtCore.QRect(510, 120, 91, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.delete_2.setFont(font)
        self.delete_2.setStyleSheet("color: rgb(97, 32, 161);")
        self.delete_2.setObjectName("delete_2")
        self.display = QtWidgets.QPushButton(Dialog)
        self.display.setGeometry(QtCore.QRect(10, 160, 591, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.display.setFont(font)
        self.display.setStyleSheet("color: rgb(97, 32, 161);")
        self.display.setObjectName("display")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(230, 10, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 170, 127);")
        self.label_3.setObjectName("label_3")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(15, 191, 581, 241))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnWidth(3, 50)
        self.tableWidget.resizeColumnsToContents()
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(10)
        self.tableWidget.horizontalHeader().setStyleSheet("QHeaderView { font-size:  12pt}")
        self.tableWidget.horizontalHeader().setStyleSheet("::section {background-color : lightGray;font-size:10pt;}")
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
      
        self.tableWidget.setHorizontalHeaderLabels(['ID', 'NAME', 'AGE', 'ADDRESS', 'SALARY'])
        self.tableWidget.setColumnWidth(0,110)
        self.tableWidget.setColumnWidth(1,110)
        self.tableWidget.setColumnWidth(2,110)
        self.tableWidget.setColumnWidth(3,110)
        self.tableWidget.setColumnWidth(4,110)
        

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def Add(self):
        id1=self.emp_id.text()
        name1=self.emp_name.text()
        age1=self.emp_age.text()
        add1=self.emp_add.text()
        sal1=self.emp_sal.text()  

        cur = conn.cursor()
        sql = "insert into COMPANY(ID,NAME,AGE,ADDRESS,SALARY) values(%s, %s, %s, %s, %s)"

        val = (id1, name1, age1, add1, sal1)
        try:
            cur.execute(sql, val)
            conn.commit()
            print("Record Inserted Succesfully")
        except:
            conn.rollback()
            print(cur.rowcount, "record inserted!")
                            

    def Update(self):
        id1=self.emp_id.text()
        name1=self.emp_name.text()
        age1=self.emp_age.text()
        add1=self.emp_add.text()
        sal1=self.emp_sal.text()   
        
        cur = conn.cursor()
        sql = "UPDATE COMPANY set NAME=%s,AGE=%s,ADDRESS=%s,SALARY=%s where ID =%s"
        
        val=(name1,age1,add1,sal1,id1)
        
        try:
            cur.execute(sql, val)
            conn.commit()
            print("Record Updated Succesfully")
        except:
            conn.rollback()
            print(cur.rowcount, "record updated!")
             
    
    def Delete(self):
        id1=self.emp_id.text()
         
        cur = conn.cursor()
        
        sql = "DELETE from COMPANY where ID =%s"
          
        
        try:
            cur.execute(sql, id1)
            conn.commit()
            print("Record Deleted Succesfully")
        except:
            conn.rollback()
            print(cur.rowcount, "record Deleted!")
            

    def Display(self):
     try:
           
            cursor = conn.cursor()
            postgreSQL_select_Query = "select * from COMPANY"

            cursor.execute(postgreSQL_select_Query)
            print("Selecting rows from COMPANY table using cursor.fetchall")
            company_records = cursor.fetchall()
            self.tableWidget.setRowCount(0)
            
            print("Print each row and it's columns values")
            for row_number,row_data in enumerate(company_records) :
                self.tableWidget.insertRow(row_number)  
                for column_number,data in enumerate(row_data):
                    item = QTableWidgetItem(str(data))
                    item.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)
                    self.tableWidget.setItem(row_number,column_number,item) 
                    
                    
            
           
                
     except (Exception, psycopg2.Error) as error:
            print("Error while fetching data from PostgreSQL", error)

      

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "EMPLOYEE INFORMATION CRUD OPERATIONS"))
        self.label.setText(_translate("Dialog", "EMPLOYEE_ ID : -"))
        self.label_2.setText(_translate("Dialog", "EMPLOYEE_ NAME : -"))
        self.label_4.setText(_translate("Dialog", "EMPLOYEE_ AGE :-"))
        self.label_5.setText(_translate("Dialog", "EMPLOYEE_ CITY :-"))
        self.label_6.setText(_translate("Dialog", "EMPLOYEE_ SALARY :-"))
        self.add.setText(_translate("Dialog", "ADD-EMP"))
        self.update.setText(_translate("Dialog", "UPDATE-EMP"))
        self.delete_2.setText(_translate("Dialog", "DELETE-EMP"))
        self.display.setText(_translate("Dialog", "SHOW RECORD"))
        self.label_3.setText(_translate("Dialog", "EMPLOYEE INFORMATION"))
        self.add.clicked.connect(self.Add)
        self.update.clicked.connect(self.Update)
        self.delete_2.clicked.connect(self.Delete)
        self.display.clicked.connect(self.Display)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
